import sqlite3
import pandas as pd
from datetime import datetime

DB_NAME = "flight_intelligence.db"

class FlightDatabase:
    def __init__(self):
        """Initialize the database connection and create tables if they don't exist."""
        self.conn = sqlite3.connect(DB_NAME, check_same_thread=False)
        self.create_tables()

    def create_tables(self):
        """Define the schema for our data warehouse."""
        cursor = self.conn.cursor()
        
        # Table 1: Raw Reviews (With a UNIQUE constraint to prevent duplicates)
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS reviews (
                id TEXT PRIMARY KEY, 
                date DATETIME,
                airline TEXT,
                rating INTEGER,
                content TEXT,
                sentiment_score REAL,
                sentiment_label TEXT
            )
        ''')

        # Table 2: Forecasts (To store our predictions)
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS forecasts (
                ds DATETIME,
                yhat REAL,
                yhat_lower REAL,
                yhat_upper REAL,
                created_at DATETIME
            )
        ''')

        # --- NEW TABLE: GEN-AI SUMMARIES ---
        # Stores the daily executive brief generated by the LLM
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS daily_summaries (
                date DATETIME PRIMARY KEY,
                airline TEXT,
                summary_text TEXT,
                generated_at DATETIME
            )
        ''')

        self.conn.commit()

    def review_exists(self, review_id):
        """Check if a specific review is already in the DB (Robustness)."""
        cursor = self.conn.cursor()
        cursor.execute('SELECT 1 FROM reviews WHERE id = ?', (review_id,))
        return cursor.fetchone() is not None

    def save_reviews(self, df):
        """
        Save a dataframe of reviews. 
        Robustness: Only inserts NEW reviews.
        """
        if df.empty:
            return 0
            
        new_count = 0
        cursor = self.conn.cursor()
        
        for _, row in df.iterrows():
            # Create a unique ID based on content hash (simple deduplication)
            review_id = str(hash(f"{row['date']}_{row['content'][:20]}"))
            
            if not self.review_exists(review_id):
                cursor.execute('''
                    INSERT INTO reviews (id, date, airline, rating, content, sentiment_score, sentiment_label)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                ''', (
                    review_id, 
                    row['date'], 
                    row['airline'], 
                    row.get('rating', 0), 
                    row['content'], 
                    row.get('sentiment_score', 0.0), 
                    row.get('sentiment_label', 'Neutral')
                ))
                new_count += 1
        
        self.conn.commit()
        print(f"✅ Database Update: Added {new_count} new reviews (Ignored {len(df) - new_count} duplicates).")

    def save_forecast(self, df):
        """Overwrite the old forecast with the new one."""
        df['created_at'] = datetime.now()
        # We replace the table content because forecasts change daily
        df.to_sql('forecasts', self.conn, if_exists='replace', index=False)
        print("✅ Database Update: Forecast refreshed.")

    # --- NEW METHOD: Save GenAI Summary ---
    def save_summary(self, date, airline, text):
        """Save the GenAI summary for a specific day."""
        cursor = self.conn.cursor()
        cursor.execute('''
            INSERT OR REPLACE INTO daily_summaries (date, airline, summary_text, generated_at)
            VALUES (?, ?, ?, ?)
        ''', (date, airline, text, datetime.now()))
        self.conn.commit()
        print(f"✅ GenAI: Summary saved for {date}")

    def get_reviews(self):
        """Fetch reviews for analysis."""
        return pd.read_sql('SELECT * FROM reviews ORDER BY date DESC', self.conn)

    def get_forecast(self):
        """Fetch the latest forecast."""
        return pd.read_sql('SELECT * FROM forecasts', self.conn)

    # --- NEW METHOD: Get Latest Summary ---
    def get_latest_summary(self):
        """Get the summary for the most recent date in the DB."""
        return pd.read_sql('SELECT * FROM daily_summaries ORDER BY date DESC LIMIT 1', self.conn)

    def close(self):
        self.conn.close()

# --- QUICK TEST ---
if __name__ == "__main__":
    db = FlightDatabase()
    print("Database initialized successfully.")
    db.close()